//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskAyazMVC.AZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookDetail
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Book_Name { get; set; }
        public string Publication { get; set; }
        public string Author { get; set; }
    }
}
